using MyBot.Backtesting.Engine;
using MyBot.Backtesting.Models;

namespace MyBot.Backtesting.Strategies;

/// <summary>Trade signal generated by a strategy.</summary>
public enum TradeSignal
{
    /// <summary>Do nothing.</summary>
    Hold,
    /// <summary>Open a long position.</summary>
    Buy,
    /// <summary>Close the current long position.</summary>
    Sell
}

/// <summary>Flexible key-value store for strategy parameters.</summary>
public class StrategyParameters : Dictionary<string, object>
{
    /// <summary>Gets a typed parameter value, or returns the default if not found.</summary>
    public T Get<T>(string key, T defaultValue = default!)
    {
        if (TryGetValue(key, out var value) && value is T typed)
            return typed;
        return defaultValue;
    }
}

/// <summary>Interface for backtestable trading strategies.</summary>
public interface IBacktestStrategy
{
    /// <summary>Human-readable name of the strategy.</summary>
    string Name { get; }
    /// <summary>Description of the strategy logic.</summary>
    string Description { get; }
    /// <summary>Initializes the strategy with parameters.</summary>
    void Initialize(StrategyParameters parameters);
    /// <summary>
    /// Called for each new candle. Returns a trade signal based on current market conditions.
    /// </summary>
    /// <param name="candle">The current candle (no look-ahead allowed).</param>
    /// <param name="portfolio">Current virtual portfolio state.</param>
    /// <param name="historicalCandles">All candles up to and including the current one.</param>
    TradeSignal OnCandle(OHLCVCandle candle, VirtualPortfolio portfolio, List<OHLCVCandle> historicalCandles);
}
